name: Deploy FastAPI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and Deploy
        env:
          OWNER: ${{ github.repository_owner }}
        run: |
          OWNER_LOWER=$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')
          docker buildx build --load -t ghcr.io/$OWNER_LOWER/stock-api:latest .
          docker push ghcr.io/$OWNER_LOWER/stock-api:latest
          
      - name: Deploy Container
        env:
          OWNER: ${{ github.repository_owner }}
        run: |
          OWNER_LOWER=$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')
          docker pull ghcr.io/$OWNER_LOWER/stock-api:latest
          docker run -d -p 8000:8000 ghcr.io/$OWNER_LOWER/stock-api:latest
